services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    command: sh -c "npm run dev"
    ports:
      - 80:5173
      - 6006:6006
