services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/node/Dockerfile
    volumes:
      - type: bind
        source: ./app
        target: /usr/src/app
    command: sh -c "npm run dev"
    ports:
      - 5173:5173
      - 6006:6006
  web:
    build:
      context: .
      dockerfile: ./infra/docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - type: bind
        source: ./app/dist
        target: /data
