name: CI
on:
  pull_request:
    branches: [main] #main向けのプルリクが作成されたときにジョブを実行
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "21.x"
      - run: npm ci #dependencyのインストール
      - run: npm  test
        env:
          CI: true #現在の環境がCI環境であることを仮定
