name: Build React on S3
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21.x

      - name: Install Dependencies
        run: cd ./app && npm install

      - name: Copy .env file
        run: cp ./app/.env.prod ./app/.env

      - name: Build
        run: cd ./app && npm run build # React ビルド

      - name: Deploy # S3にデプロイ
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp app/dist s3://osake-db-site --recursive  --region us-east-1
